### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Tfausx** [TesterTesterov/mesScriptAsseAndDissasembler#1]
Hello, i hope you're having a great day! I was wondering if with this tool can be edited the texts of .mes archives (not engine part, just ingame texts), I tried it this tool with Adabana Odd Tales, but doesn't seems to have a ingame text at all

![imagen](https://user-images.githubusercontent.com/29191836/109111045-f9de1880-7716-11eb-9dff-d7d631a97847.png)

Thanks in advance!

**Comment by TesterTesterov** [comment]
The tool can edit in-games texts. when they are in .mes _scripts._

Well, in case of this particular game, text may be or in some other script, or in some other place. If texts in some .mes script, it should work. Otherwise I think no.

Then, I'll do some testing on this matter as I get the game...

**Comment by TesterTesterov** [comment]
I did find the game texts. Well, it's quite uncommon for this engine, but... it's on MAP files in data.arc. Strings somehow _injects_ from MAP files to scripts then a message is coming.

This tool is just for MES scripts, not for MAP. But I'll create a specific tool for this game (pretty soon, I hope).

**Comment by TesterTesterov** [comment]
Okay, it's ready.

Try [MAPTool](https://github.com/TesterTesterov/MAPTool) with .MAP files in data.arc.

**Comment by Tfausx** [comment]
Thank you very much for your time to make that tool, can extact and repack perfectly! I just have one last question (if you can help me with that of course), how i can repack to .arc again? (I try left the folder with modified archives in the game directory but not work) I was checking about a tool in this repository:

https://github.com/regomne/chinesize/tree/master/Silky/extarc

But it's on a .go format and i haven't no idea how to run / compile that on windows, if is not much problem, you can give me a hand with that?

Thank you very much again for this!

**Comment by TesterTesterov** [comment]
Well, about it... Usually you don't need to repack .arc to modify the game on this engine.
But this case may be different...

This Silky arc file structure as follows:
- First goes... as I remember correctly, unsigned int for number of entries.
- Next goes some number (number of entries) of structures as follows: 
- - Byte, defines an entry name length (in bytes).
- - Entry name. It's obfucificated. To decrypt +1 in the last byte of string, + 2 in byte before the last and so on.
- - Next is unsigned int in reversed byte order.  If I remember correctly, it's a uncompressed entry length.
- - Unsigned int in reversed byte order. If I remember correctly, it's an a compressed entry length.
- - Unsigned int in reversed byte order. If I remember correctly, it's an offset of entry.
- Next goes data, compressed with lzss.

It wouldn't be hard to make a tool to pack files in the archives, but, as I saw sometimes, "lzss" module in Python often works incorrectly, so I would need to write my own implementation of lzss, which could take some time.

I'll do some testing about how to modify the game without repacking, when I'll have time.
Otherwise I'll do something about lzss.

===
As for that Golang script, it's not working very good with me too.

**Comment by TesterTesterov** [comment]
No, there is no need to actually repack arc archives. You can just put the modified file in the game folder. Just don't delete the archive itself.

> I try left the folder with modified archives in the game directory but not work
- What's the problem exactly?

![image](https://user-images.githubusercontent.com/66121918/109272340-a6e48e00-7808-11eb-9cf4-2a5e9d4ab283.png)

**Comment by Tfausx** [comment]
Well, i did everything you say before:

-Uncompress data.arc and put the modified scripts inside of that.

Then i left both (uncompressed data folder + data.arc) but the game doesn't recognize the modified script (maybe this not work will all releases?) It's weird, i left you an screenshot of what i did

![1](https://user-images.githubusercontent.com/29191836/109313488-0ce00e00-7827-11eb-8e53-407a6f88293c.png)

Thanks again for your time and support!

**Comment by TesterTesterov** [comment]
> It's weird, i left you an screenshot of what i did
- Ah, I know the problem of your's.
- You need to put extracted files not in subfolder "data" in the game folder, but **in the game folder itself**. In the folder, where the exe of it resides.

**Comment by Tfausx** [comment]
And that's resolve the problem! Thank you very much for your time, patience and kindness!

Have a nice day!

**Comment by Cosetto** [comment]
Just want to ask if you figure out how to repack it? It would be a pain to put those MES files in the directory

**Comment by TesterTesterov** [comment]
> Just want to ask if you figure out how to repack it? It would be a pain to put those MES files in the directory

You may want to try [extarc](https://github.com/regomne/chinesize/tree/master/Silky/extarc), as was written below.

**Comment by Cosetto** [comment]
> > Just want to ask if you figure out how to repack it? It would be a pain to put those MES files in the directory
> 
> You may want to try [extarc](https://github.com/regomne/chinesize/tree/master/Silky/extarc), as was written below.

Same question as the guy above, I  don't know compile that .go into executable. Can you help?

**Comment by TesterTesterov** [comment]
First, install [GoLang](https://golang.org/).
Next, use "go build arc.go" command in command line while having the arc.go directory as active.
Theoretically it should work. Otherwise you'd need to install some dependancies for the building to success.

**Comment by Cosetto** [comment]
> First, install [GoLang](https://golang.org/).
> Next, use "go build arc.go" command in command line while having the arc.go directory as active.
> Theoretically it should work. Otherwise you'd need to install some dependancies for the building to success.

![image](https://user-images.githubusercontent.com/81801486/132155901-11e35f1f-b332-41b0-a465-b6ee6e1b552d.png)
I repacked it but it doesn't have compressed option too bad

**Comment by TesterTesterov** [comment]
Too bad, since I have no better tools.
I had created a tool for Silky .arc repacking long ago, but it seems Python lzss from lzss library (one I used) is not compatible with this lzss. And it would be a pain to implement otherwise. So it won't work.

**Comment by TesterTesterov** [comment]
> I repacked it but it doesn't have compressed option too bad

Okay, @Cosetto, I hath finally dealed with this pain and implemented Silky Engine's type of LZSS compression (both decompression + compression). See [SilkyArcTool](https://github.com/TesterTesterov/SilkyArcTool). Now you can repack it with proper compression just fine (as far as I tested).

**Comment by Cosetto** [comment]
Nice

**Comment by Cosetto** [comment]
- btw did you test if it can read from update.arc? Sekai made adult patch of [link](https://vndb.org/v26000) by update.arc

**Comment by TesterTesterov** [comment]
> * btw did you test if it can read from update.arc? Sekai made adult patch of [link](https://vndb.org/v26000) by update.arc

I have tested the archive. From what I have seen, it is the normal Silky arc indeed and therefore the tool should work with it, albeit it probably will take a lot of time to extract/repack data from it. (Sometime I will need to drastically optimize (de)compression algorithm from that tool to make it fater).

**Comment by TesterTesterov** [comment]
I'll see about that update.arc now, since I have ended hacking all scripts and archives of AI5WIN. AI6WIN and Silky Engine by now.

**Comment by TesterTesterov** [comment]
@Cosetto, seems it is not. I'll work on solution now.

**Comment by Cosetto** [comment]
![image](https://user-images.githubusercontent.com/81801486/147558229-b134c545-90b5-4895-bb13-fd9292d5065f.png)
[Kimagure Temptation.zip](https://github.com/TesterTesterov/mesScriptAsseAndDisassembler/files/7784243/Kimagure.Temptation.zip)
I just double check their update.arc and saw two weird files

**Comment by TesterTesterov** [comment]
@Cosetto, okay, got it supported now (in [SilkyArcTool 1.1](https://github.com/TesterTesterov/SilkyArcTool/releases/tag/1.1)).
Basically, it was an archive with unencrypted data. I added in the program extraction of uncompressed data + option to pack an archive without compressing data.

ANNEVIEWER.AREA is not relevant for reading these files. As for BUILDINFO... Well, I looked into it and it indeed contain information about the archive that was built. So I did check, is it relevant for reading files from the archive, in the following manner. I deleted it, repacked the update.arc and inserted it into the game folder. It worked (data from update.arc was found). Therefore I conclude it is not relevant too.

So it should be supported now.

**Comment by Cosetto** [comment]
thank you

**Comment by Cosetto** [comment]
There's another note on Silky's engine: in save folder(usually in C:\Users\[Pc name]\AppData\Roaming\Silkys\[Game name]\save when installing the game) search for .xml in the save folder, in that will have this: 
![image](https://user-images.githubusercontent.com/81801486/147575432-ea9bbdfa-c822-4069-bd19-7889cc2ecc05.png)
This is where to change font of Silky without using hex editor

**Comment by TesterTesterov** [comment]
@Cosetto, I indeed know about this method. Yet sometimes Silky Engine generate that xml file (if I remember correctly from my previous testing) based on defaults, so you need to run the game at least once (not in all cases, sometime Silky Engine just won't start without what file and some more) for it to appear. And for it to appear with "crytchy font" you need to HEX-edit.

Also the backward statement is also true: if it already exist, Silky Engine may not change font, even if you change it in exe, unless you edit that XML-file.
