### ISSUE TITLE
Directory disassembly fails if path contains ".."

### ISSUE THREAD

**Issue by arcusmaximus** [TesterTesterov/mesScriptAsseAndDissasembler#3]
If the .mes folder path contains "..", disassembly fails with a whole bunch of "file not found" errors.

Example:
- Extract .mes files to \<game folder\>\mes
- Create folder \<game folder\>\txt
- Extract mesScriptAsseAndDisassembler to \<game folder\>\tool
- Launch the tool, switch from "Single file" to "Directory", and select the "mes" and "txt" folders using the "..." buttons (-> textboxes get filled with "..\mes" and "..\txt")
- Click "Disassemble"

This results in a whole bunch of errors like "No such file or directory: ..\\mes\\mes\\sis4_02_02_kiyomi_h1.mes" (notice the duplicate folder name).

**Comment by TesterTesterov** [comment]
Quite strange... I'll see as I have time.

**Comment by TesterTesterov** [comment]
Okay, got the problem. Some file handling abnormalities... Fix will be ready soon.

**Comment by TesterTesterov** [comment]
@arcusmaximus, fixed. Try [1.3 version](https://github.com/TesterTesterov/mesScriptAsseAndDisassembler/releases/tag/1.3).

**Comment by TesterTesterov** [comment]
As there was no answer, I assure there is not problem anymore.
